version: "3"

services:
  openms:
    image: dmccloskey/docker-openms-vscode
    volumes:
      # - //C/Users/domccl/Dropbox (UCSD SBRG)/Project_FastPeak/openMS_MRMworkflow/:/home/user/openMS_MRMworkflow/
      - //C/Users/domccl/GitHub/smartPeak/cpp/:/home/user/code/
      # - //C/Users/dmccloskey/Dropbox (UCSD SBRG)/Project_FastPeak/openMS_MRMworkflow/:/home/user/openMS_MRMworkflow/
      # - //C/Users/dmccloskey/Documents/GitHub/smartPeak/cpp/:/home/user/code/
      # - /home/systemsbiochemistry/Documents/openMS_MRMworkflow/:/home/user/openMS_MRMworkflow/
      # - /home/systemsbiochemistry/Documents/GitHub/smartPeak/cpp/:/home/user/code/
    # ports:
    #   - "3000:3000"
    #   - "22:22"
    privileged: true
    security_opt:
      - seccomp:unconfined #https://github.com/docker/compose/issues/2813
    #command: python /home/user/code/debug_remote.py
    restart: always
    networks:
      - openms_network
    
networks:
  openms_network:
    ipam:
      config:
        - subnet: 172.23.0.0/16